# Generated by Django 2.1.1 on 2019-02-19 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('locker', '0001_initial'), ('locker', '0002_auto_20150228_1227'), ('locker', '0003_registrationrequest'), ('locker', '0004_auto_20161017_1621'), ('locker', '0005_add_ownership'), ('locker', '0006_migrate_data_to_ownerships'), ('locker', '0007_remove_unused_models'), ('locker', '0008_remove_firstlast_name_registrationrequest')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('CU1-111', 'CU1-111'), ('CU2-021', 'CU2-021'), ('EU1-110', 'EU1-110')], editable=False, max_length=10, verbose_name='Rom')),
                ('locker_number', models.IntegerField(editable=False, verbose_name='Skapnummer')),
            ],
            options={
                'verbose_name': 'Skap',
                'verbose_name_plural': 'Skap',
            },
        ),
        migrations.AlterUniqueTogether(
            name='locker',
            unique_together={('room', 'locker_number')},
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_token', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Tidspunktet skapet ble forsøkt registrert.')),
                ('username', models.CharField(max_length=30, verbose_name='Brukernavn')),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locker.Locker', verbose_name='Skap')),
                ('confirmation_time', models.DateTimeField(blank=True, null=True, verbose_name='Tidspunktet forspørselen ble bekreftet')),
            ],
            options={
                'verbose_name': 'Skapforespørsel',
                'verbose_name_plural': 'Skapforespørsler',
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_reserved', models.DateTimeField(null=True)),
                ('time_unreserved', models.DateTimeField(blank=True, null=True)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locker.Locker', verbose_name='Skap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bruker')),
            ],
            options={'verbose_name': 'Eierforhold', 'verbose_name_plural': 'Eierforhold'},
        ),
    ]
