# Generated by Django 2.1.7 on 2019-08-16 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0001_squashed_0008_remove_firstlast_name_registrationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='reserved',
            field=models.BooleanField(default=False, verbose_name='Er reservert'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='reserved_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Utløp av reservasjonsperioden, normalt 14 dager etter creation_time'),
        ),
    ]
