# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0002_auto_20150228_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_token', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Tidspunktet skapet ble forsøkt registrert.')),
                ('username', models.CharField(max_length=30, verbose_name='Brukernavn')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Fornavn')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Etternavn')),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, verbose_name='Skap', to='locker.Locker')),
            ],
        ),
    ]
