# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0003_registrationrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inactivelockerreservation',
            options={'verbose_name': 'Inaktiv registrering', 'verbose_name_plural': 'Inaktive registreringer'},
        ),
        migrations.AlterModelOptions(
            name='locker',
            options={'verbose_name': 'Skap', 'verbose_name_plural': 'Skap'},
        ),
        migrations.AlterModelOptions(
            name='registrationrequest',
            options={'verbose_name': 'Skapforespørsel', 'verbose_name_plural': 'Skapforespørsler'},
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='confirmation_time',
            field=models.DateTimeField(null=True, verbose_name='Tidspunktet forspørselen ble bekreftet'),
        ),
    ]
