# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 15:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locker', '0004_auto_20161017_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_reserved', models.DateTimeField(null=True)),
                ('lock_cut', models.BooleanField()),
                ('time_unreserved', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inactivelockerreservation',
            name='locker',
        ),
        migrations.RemoveField(
            model_name='inactivelockerreservation',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='time_reserved',
        ),
        migrations.DeleteModel(
            name='InactiveLockerReservation',
        ),
        migrations.AddField(
            model_name='ownership',
            name='locker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locker.Locker', verbose_name='Skap'),
        ),
        migrations.AddField(
            model_name='ownership',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Skap'),
        ),
    ]
