# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0005_auto_20171012_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locker.Ownership'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='lock_cut',
            field=models.BooleanField(default=False),
        ),
    ]
