# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 18:20
from __future__ import unicode_literals

from django.db import migrations

def migrate_data_to_ownership(apps, schema_editor):
    Locker = apps.get_model('locker', 'Locker')
    InactiveLockerReservation = apps.get_model('locker', 'InactiveLockerReservation')
    Ownership = apps.get_model('locker', 'Ownership')

    for locker in Locker.objects.all():
        if locker.owner is not None:
            ownership = Ownership()
            ownership.locker=locker
            ownership.user=locker.owner
            ownership.time_reserved = locker.time_reserved
            ownership.save()
    for inactive_reservation in InactiveLockerReservation.objects.all():
        ownership = Ownership()
        ownership.locker = inactive_reservation.locker
        ownership.user = inactive_reservation.owner
        ownership.time_reserved = inactive_reservation.time_reserved
        ownership.time_unreserved = inactive_reservation.time_unreserved
        ownership.save()
        

class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0005_add_ownership'),
    ]

    operations = [
        migrations.RunPython(migrate_data_to_ownership),
    ]
