# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0006_auto_20171012_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownership',
            name='lock_cut',
        ),
        migrations.RemoveField(
            model_name='registrationrequest',
            name='ownership',
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='confirmation_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tidspunktet forspørselen ble bekreftet'),
        ),
    ]
