# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0006_migrate_data_to_ownerships'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InactiveLockerReservation',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='time_reserved',
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='confirmation_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tidspunktet forspørselen ble bekreftet'),
        ),
    ]
