# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0007_auto_20171016_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownership',
            old_name='owner',
            new_name='user',
        ),
    ]
