# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-09 14:53
#
# Removes first and last name in userrequests
#

from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0007_remove_unused_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrequest',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registrationrequest',
            name='last_name',
        ),
    ]
